# vim: set filetype=yaml.docker-compose :
services:
  lfs:
    image: 'ghcr.io/naoya0117/linux-from-scratch:${ENV-dev}-${ARCH-x86_64}'
    build:
      context: './docker-dev/lfs/'
      dockerfile: 'fedora.Dockerfile'
      args:
        - UID=${UID-1000}
        - GID=${GID-1000}
    volumes:
      - './lfs-root/:/mnt/lfs'
      - './logs:/home/nonroot/lfs-logs/'
      - './bin/:/home/nonroot/bin/'
      - './docs/:/home/nonroot/docs/'
    tty: true
    stdin_open: true
